---
apiVersion: apps/v1
kind: Deployment    # K8s resource kind we are creating
metadata:
  name: backend-springboot-book
spec:
  selector:
    matchLabels:
      app: backend-springboot-book
  replicas: 2       # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: backend-springboot-book
    spec:
      containers:
        - name: backend-springboot-book
          image: raulrobinson/backend-springboot-book:v1.0.0 # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8080           # The port that the container is running on in the cluster
---
apiVersion: v1  # Kubernetes API version
kind: Service   # K8s resource kind we are creating
metadata:       # Metadata of the resource kind we are creating
  name: backend-springboot-book-svc
spec:
  selector:
    app: backend-springboot-book
  ports:
    - protocol: "TCP"
      port: 8080        # The port that the service is running on in the cluster
      targetPort: 8080  # The port exposed by the service
  type: NodePort        # type of the service.
---